//! OAuth flow logic — pure decisions, no network and no randomness.
//!
//! Ported from `src/main/cloud/oauth.ts`. The Electron code mixed `crypto`
//! random generation, `shell.openExternal`, an `http` loopback server, and
//! `fetch` to the token endpoint together with the *decisions* about how to
//! shape requests and validate the callback. Here we keep only the decisions:
//!
//!   - deriving the PKCE challenge from a verifier ([`pkce_challenge`]),
//!   - building the authorization URL ([`build_auth_url`]) and the token-exchange / refresh request bodies ([`build_token_exchange_body`], [`build_refresh_body`]),
//!   - turning a token-endpoint JSON body into a [`TokenResponse`] with an absolute `expires_at` ([`parse_token_response`]),
//!   - validating the loopback callback's query params, including CSRF state-matching and replay protection ([`parse_loopback_callback`], [`StateReplayGuard`]),
//!   - classifying a refresh failure so the caller knows when to force reauth ([`classify_refresh_error`]).
//!
//! The `src-tauri` shell owns the impure half: generating the random verifier
//! and state, opening the browser, running the loopback `TcpListener`, and
//! POSTing the bodies built here. Google uses the Desktop **loopback** flow
//! (`http://127.0.0.1:<port>`) for all three services — there is no custom-scheme
//! path (that was Dropbox/OneDrive, now dropped).

use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;

use super::TokenResponse;

/// How long a pending OAuth flow / used-state entry lives. Matches the Electron
/// `STATE_TTL_MS` / `PENDING_TIMEOUT_MS` (10 min — long enough for a slow
/// consent screen).
pub const STATE_TTL_MS: i64 = 10 * 60_000;
/// Hard cap on the replay-guard map so a flood of OAuth attempts can't grow it
/// unboundedly (`oauth.ts:37` `MAX_USED_STATES`).
pub const MAX_USED_STATES: usize = 256;

/// Things that can go wrong validating an OAuth callback or token response.
/// Messages mirror the Electron `Error` strings so logs/telemetry carry across.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum OAuthError {
    /// The provider returned `?error=...` (user denied, etc.).
    #[error("OAuth nektet: {0}")]
    Denied(String),
    /// Returned `state` did not match the value we issued — possible CSRF.
    #[error("OAuth state mismatch — mulig CSRF-forsøk")]
    StateMismatch,
    /// `state` matched but we have already consumed it this session — replay.
    #[error("OAuth state gjenbrukt — avvist")]
    StateReplay,
    /// Callback arrived without the `code` parameter.
    #[error("OAuth callback manglet code-parameter")]
    MissingCode,
    /// Token-endpoint body was not the JSON shape we expected.
    #[error("OAuth token-svar uleselig: {0}")]
    Parse(String),
}

/// base64url-encode (no padding) — the encoding PKCE and the random state/
/// verifier use throughout the Google flow (`oauth.ts:base64url`).
pub fn base64url(bytes: &[u8]) -> String {
    URL_SAFE_NO_PAD.encode(bytes)
}

/// Derive the PKCE `code_challenge` from a verifier: base64url(SHA-256(verifier)),
/// the `S256` method (RFC 7636 §4.2). Deterministic — the random verifier itself
/// is generated by the shell.
pub fn pkce_challenge(verifier: &str) -> String {
    let digest = Sha256::digest(verifier.as_bytes());
    base64url(&digest)
}

/// Serialise key/value pairs as `application/x-www-form-urlencoded`, byte-for-byte
/// like the JS `URLSearchParams` serializer the Electron code relied on: space
/// becomes `+`, the unreserved set `A-Z a-z 0-9 * - . _` passes through, and
/// everything else is `%XX` (uppercase hex). Used for both the auth-URL query
/// string and the token-request bodies.
pub fn encode_form(pairs: &[(&str, &str)]) -> String {
    fn push_encoded(out: &mut String, s: &str) {
        for &b in s.as_bytes() {
            match b {
                b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'*' | b'-' | b'.' | b'_' => {
                    out.push(b as char)
                }
                b' ' => out.push('+'),
                _ => {
                    out.push('%');
                    out.push(
                        char::from_digit((b >> 4) as u32, 16)
                            .unwrap()
                            .to_ascii_uppercase(),
                    );
                    out.push(
                        char::from_digit((b & 0xf) as u32, 16)
                            .unwrap()
                            .to_ascii_uppercase(),
                    );
                }
            }
        }
    }
    let mut out = String::new();
    for (i, (k, v)) in pairs.iter().enumerate() {
        if i > 0 {
            out.push('&');
        }
        push_encoded(&mut out, k);
        out.push('=');
        push_encoded(&mut out, v);
    }
    out
}

/// Decode a callback URL's query string into `(key, value)` pairs, the input
/// [`parse_loopback_callback`] expects. Accepts a bare query, a `path?query`, or
/// a full URL; `+` → space and `%XX` → byte (the inverse of [`encode_form`]).
/// Invalid `%` escapes are left intact so a stray `%` never drops a pair. Pure.
pub fn decode_query_pairs(raw: &str) -> Vec<(String, String)> {
    let after_q = raw.split_once('?').map(|(_, q)| q).unwrap_or(raw);
    // Tolerate a trailing fragment or whitespace (e.g. a raw HTTP request line).
    let query = after_q
        .split(|c: char| c == '#' || c.is_whitespace())
        .next()
        .unwrap_or("");
    query
        .split('&')
        .filter(|s| !s.is_empty())
        .map(|pair| {
            let (k, v) = pair.split_once('=').unwrap_or((pair, ""));
            (decode_component(k), decode_component(v))
        })
        .collect()
}

/// Percent-decode one form component (`%XX` → byte, `+` → space).
fn decode_component(s: &str) -> String {
    let bytes = s.as_bytes();
    let mut out: Vec<u8> = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        match bytes[i] {
            b'+' => {
                out.push(b' ');
                i += 1;
            }
            b'%' if i + 2 < bytes.len() => {
                match (hex_nibble(bytes[i + 1]), hex_nibble(bytes[i + 2])) {
                    (Some(hi), Some(lo)) => {
                        out.push(hi << 4 | lo);
                        i += 3;
                    }
                    _ => {
                        out.push(b'%');
                        i += 1;
                    }
                }
            }
            b => {
                out.push(b);
                i += 1;
            }
        }
    }
    String::from_utf8_lossy(&out).into_owned()
}

fn hex_nibble(b: u8) -> Option<u8> {
    match b {
        b'0'..=b'9' => Some(b - b'0'),
        b'a'..=b'f' => Some(b - b'a' + 10),
        b'A'..=b'F' => Some(b - b'A' + 10),
        _ => None,
    }
}

/// Build the Google authorization URL for the Desktop loopback flow. Mirrors the
/// `params` block in `openGoogleAuthWithScope` (`oauth.ts:190`): `access_type=
/// offline` + `prompt=consent` so we always get a refresh token.
pub fn build_auth_url(
    auth_url: &str,
    client_id: &str,
    redirect_uri: &str,
    state: &str,
    challenge: &str,
    scope: &str,
) -> String {
    let query = encode_form(&[
        ("client_id", client_id),
        ("redirect_uri", redirect_uri),
        ("response_type", "code"),
        ("state", state),
        ("code_challenge", challenge),
        ("code_challenge_method", "S256"),
        ("scope", scope),
        ("access_type", "offline"),
        ("prompt", "consent"),
    ]);
    format!("{auth_url}?{query}")
}

/// Build the `authorization_code` token-exchange request body (`oauth.ts:324`).
/// Google requires `client_secret` even for Desktop+PKCE clients, so it is sent
/// when present (it is not truly secret for installed apps per Google's docs).
pub fn build_token_exchange_body(
    client_id: &str,
    client_secret: Option<&str>,
    redirect_uri: &str,
    code: &str,
    verifier: &str,
) -> String {
    let mut pairs = vec![
        ("client_id", client_id),
        ("redirect_uri", redirect_uri),
        ("grant_type", "authorization_code"),
        ("code", code),
        ("code_verifier", verifier),
    ];
    if let Some(secret) = client_secret.filter(|s| !s.is_empty()) {
        pairs.push(("client_secret", secret));
    }
    encode_form(&pairs)
}

/// Build the `refresh_token` request body (`oauth.ts:364`).
pub fn build_refresh_body(
    client_id: &str,
    client_secret: Option<&str>,
    refresh_token: &str,
) -> String {
    let mut pairs = vec![
        ("client_id", client_id),
        ("grant_type", "refresh_token"),
        ("refresh_token", refresh_token),
    ];
    if let Some(secret) = client_secret.filter(|s| !s.is_empty()) {
        pairs.push(("client_secret", secret));
    }
    encode_form(&pairs)
}

/// Parse a token-endpoint JSON body into a [`TokenResponse`], resolving
/// `expires_in` (seconds) to an absolute `expires_at` (unix ms) using the
/// caller-supplied `now_ms` — exactly what `exchangeCode`/`refreshAccessToken`
/// compute with `Date.now() + expires_in * 1000` (`oauth.ts:348`).
pub fn parse_token_response(body: &str, now_ms: i64) -> Result<TokenResponse, OAuthError> {
    let v: serde_json::Value =
        serde_json::from_str(body).map_err(|e| OAuthError::Parse(e.to_string()))?;
    let access_token = v
        .get("access_token")
        .and_then(|x| x.as_str())
        .ok_or_else(|| OAuthError::Parse("manglet access_token".into()))?
        .to_string();
    let refresh_token = v
        .get("refresh_token")
        .and_then(|x| x.as_str())
        .map(|s| s.to_string());
    let expires_at = v
        .get("expires_in")
        .and_then(|x| x.as_i64())
        .map(|secs| now_ms + secs * 1000);
    Ok(TokenResponse {
        access_token,
        refresh_token,
        expires_at,
    })
}

/// Bounded, self-GCing record of OAuth `state` values already consumed this
/// session. Mirrors the `usedStates` map in `oauth.ts`: matching state is
/// necessary but not sufficient — a state seen twice (e.g. a browser pre-fetch
/// double-callback) is rejected. Entries auto-expire after [`STATE_TTL_MS`] and
/// the size is capped at [`MAX_USED_STATES`].
///
/// Pure: every method takes `now_ms` rather than reading the clock, so the
/// shell owns wall-time and tests stay deterministic.
#[derive(Debug, Default)]
pub struct StateReplayGuard {
    /// state → expiresAt (unix ms). `BTreeMap` so the "drop oldest" eviction is
    /// deterministic by key (the Electron map relied on insertion order; for a
    /// defensive cap any stable victim is fine and ordered is easiest to test).
    used: BTreeMap<String, i64>,
}

impl StateReplayGuard {
    pub fn new() -> Self {
        Self::default()
    }

    /// True if `state` was already consumed and is still within its TTL. Expired
    /// entries are dropped lazily and treated as not-replayed.
    pub fn is_replayed(&mut self, state: &str, now_ms: i64) -> bool {
        match self.used.get(state) {
            None => false,
            Some(&exp) if exp < now_ms => {
                self.used.remove(state);
                false
            }
            Some(_) => true,
        }
    }

    /// Record `state` as consumed. GCs expired entries on every insert (cheap —
    /// OAuth flows are rare) and enforces the size cap by dropping the oldest.
    pub fn mark_used(&mut self, state: &str, now_ms: i64) {
        self.used.retain(|_, &mut exp| exp >= now_ms);
        if self.used.len() >= MAX_USED_STATES {
            if let Some(first) = self.used.keys().next().cloned() {
                self.used.remove(&first);
            }
        }
        self.used.insert(state.to_string(), now_ms + STATE_TTL_MS);
    }
}

/// Validate the loopback redirect's query params and extract the authorization
/// code. Mirrors the callback handler in `openGoogleAuthWithScope`
/// (`oauth.ts:161`): provider `error` first, then CSRF state-match, then replay
/// rejection (recording the state as used on success), then the `code`.
///
/// `query` is the decoded `(key, value)` list from the callback URL. On `Ok` the
/// `state` has been marked consumed in `replay`.
pub fn parse_loopback_callback(
    query: &[(String, String)],
    expected_state: &str,
    replay: &mut StateReplayGuard,
    now_ms: i64,
) -> Result<String, OAuthError> {
    let get = |key: &str| {
        query
            .iter()
            .find(|(k, _)| k == key)
            .map(|(_, v)| v.as_str())
    };

    if let Some(err) = get("error") {
        let desc = get("error_description").unwrap_or(err);
        return Err(OAuthError::Denied(desc.to_string()));
    }
    let returned_state = get("state").unwrap_or("");
    if returned_state != expected_state {
        return Err(OAuthError::StateMismatch);
    }
    if replay.is_replayed(returned_state, now_ms) {
        return Err(OAuthError::StateReplay);
    }
    replay.mark_used(returned_state, now_ms);
    match get("code") {
        Some(code) if !code.is_empty() => Ok(code.to_string()),
        _ => Err(OAuthError::MissingCode),
    }
}

/// Why a token refresh failed. `InvalidGrant` means the refresh token is dead
/// (revoked / expired) — the caller must flag the connection `needsReauth`
/// rather than retrying. Everything else is treated as transient/other and may
/// be retried (`oauth.ts:378` reads the `error` field for `invalid_grant`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RefreshErrorKind {
    /// `error: "invalid_grant"` — refresh token revoked; force reauth.
    InvalidGrant,
    /// Any other failure (network, 5xx, malformed) — retryable.
    Other,
}

/// Classify a failed-refresh response body. Looks for the OAuth `error` field
/// equal to `invalid_grant`; on any parse failure falls back to `Other`.
pub fn classify_refresh_error(body: &str) -> RefreshErrorKind {
    match serde_json::from_str::<serde_json::Value>(body) {
        Ok(v) if v.get("error").and_then(|e| e.as_str()) == Some("invalid_grant") => {
            RefreshErrorKind::InvalidGrant
        }
        _ => RefreshErrorKind::Other,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn decode_query_pairs_handles_url_query_and_request_line() {
        // Full redirect URL with encoded values + a "+"-as-space.
        let pairs =
            decode_query_pairs("http://127.0.0.1:5712/?code=4%2Fabc&state=xyz&scope=a+b#frag");
        assert_eq!(pairs[0], ("code".to_string(), "4/abc".to_string()));
        assert_eq!(pairs[1], ("state".to_string(), "xyz".to_string()));
        assert_eq!(pairs[2], ("scope".to_string(), "a b".to_string()));
        // Bare query works too, and round-trips with encode_form for safe input.
        let bare = decode_query_pairs("error=access_denied&error_description=No+thanks");
        assert_eq!(bare[1].1, "No thanks");
        // A stray percent is preserved, not dropped.
        assert_eq!(decode_query_pairs("code=a%zz")[0].1, "a%zz");
    }

    // RFC 7636 Appendix B test vector — the canonical PKCE example.
    #[test]
    fn pkce_challenge_matches_rfc7636_vector() {
        let verifier = "dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk";
        assert_eq!(
            pkce_challenge(verifier),
            "E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM"
        );
    }

    #[test]
    fn base64url_has_no_padding_and_url_alphabet() {
        // 0xfb 0xff -> standard base64 "+/8=" ; url-safe no-pad -> "-_8"
        assert_eq!(base64url(&[0xfb, 0xff]), "-_8");
    }

    #[test]
    fn encode_form_matches_urlsearchparams_semantics() {
        // space -> '+', ':' and '/' percent-encoded, unreserved '*-._' kept.
        assert_eq!(
            encode_form(&[("scope", "a b:c/d"), ("x", "*-._")]),
            "scope=a+b%3Ac%2Fd&x=*-._"
        );
    }

    #[test]
    fn auth_url_carries_offline_consent_and_pkce() {
        let url = build_auth_url(
            "https://accounts.google.com/o/oauth2/v2/auth",
            "client123",
            "http://127.0.0.1:5000",
            "STATE",
            "CHAL",
            "scope.a scope.b",
        );
        assert!(url.starts_with("https://accounts.google.com/o/oauth2/v2/auth?"));
        assert!(url.contains("code_challenge=CHAL"));
        assert!(url.contains("code_challenge_method=S256"));
        assert!(url.contains("access_type=offline"));
        assert!(url.contains("prompt=consent"));
        assert!(url.contains("redirect_uri=http%3A%2F%2F127.0.0.1%3A5000"));
        assert!(url.contains("scope=scope.a+scope.b"));
    }

    #[test]
    fn token_exchange_body_includes_secret_only_when_present() {
        let with =
            build_token_exchange_body("cid", Some("sek"), "http://127.0.0.1:1", "CODE", "VER");
        assert!(with.contains("grant_type=authorization_code"));
        assert!(with.contains("code=CODE"));
        assert!(with.contains("code_verifier=VER"));
        assert!(with.contains("client_secret=sek"));

        let without = build_token_exchange_body("cid", None, "http://127.0.0.1:1", "CODE", "VER");
        assert!(!without.contains("client_secret"));
        // Empty secret is treated the same as absent.
        let empty = build_token_exchange_body("cid", Some(""), "http://127.0.0.1:1", "CODE", "VER");
        assert!(!empty.contains("client_secret"));
    }

    #[test]
    fn refresh_body_shape() {
        let b = build_refresh_body("cid", Some("sek"), "RT");
        assert!(b.contains("grant_type=refresh_token"));
        assert!(b.contains("refresh_token=RT"));
        assert!(b.contains("client_secret=sek"));
    }

    #[test]
    fn parse_token_response_resolves_expiry_against_now() {
        let body = r#"{"access_token":"AT","refresh_token":"RT","expires_in":3600}"#;
        let tok = parse_token_response(body, 1_000_000).unwrap();
        assert_eq!(tok.access_token, "AT");
        assert_eq!(tok.refresh_token.as_deref(), Some("RT"));
        assert_eq!(tok.expires_at, Some(1_000_000 + 3_600_000));
    }

    #[test]
    fn parse_token_response_without_expiry_or_refresh() {
        let tok = parse_token_response(r#"{"access_token":"AT"}"#, 5).unwrap();
        assert_eq!(tok.refresh_token, None);
        assert_eq!(tok.expires_at, None);
    }

    #[test]
    fn parse_token_response_missing_access_token_is_error() {
        assert!(matches!(
            parse_token_response(r#"{"refresh_token":"RT"}"#, 0),
            Err(OAuthError::Parse(_))
        ));
        assert!(matches!(
            parse_token_response("not json", 0),
            Err(OAuthError::Parse(_))
        ));
    }

    fn q(pairs: &[(&str, &str)]) -> Vec<(String, String)> {
        pairs
            .iter()
            .map(|(k, v)| (k.to_string(), v.to_string()))
            .collect()
    }

    #[test]
    fn callback_happy_path_returns_code_and_consumes_state() {
        let mut guard = StateReplayGuard::new();
        let query = q(&[("state", "S1"), ("code", "AUTHCODE")]);
        assert_eq!(
            parse_loopback_callback(&query, "S1", &mut guard, 0).unwrap(),
            "AUTHCODE"
        );
        // Second identical callback is now a replay.
        assert!(matches!(
            parse_loopback_callback(&query, "S1", &mut guard, 1),
            Err(OAuthError::StateReplay)
        ));
    }

    #[test]
    fn callback_error_param_takes_precedence() {
        let mut guard = StateReplayGuard::new();
        let query = q(&[
            ("error", "access_denied"),
            ("error_description", "User said no"),
        ]);
        assert_eq!(
            parse_loopback_callback(&query, "S1", &mut guard, 0),
            Err(OAuthError::Denied("User said no".into()))
        );
    }

    #[test]
    fn callback_state_mismatch_and_missing_code() {
        let mut guard = StateReplayGuard::new();
        assert_eq!(
            parse_loopback_callback(
                &q(&[("state", "WRONG"), ("code", "C")]),
                "S1",
                &mut guard,
                0
            ),
            Err(OAuthError::StateMismatch)
        );
        assert_eq!(
            parse_loopback_callback(&q(&[("state", "S1")]), "S1", &mut guard, 0),
            Err(OAuthError::MissingCode)
        );
    }

    #[test]
    fn state_replay_guard_expires_after_ttl() {
        let mut guard = StateReplayGuard::new();
        guard.mark_used("S", 0);
        assert!(guard.is_replayed("S", STATE_TTL_MS - 1));
        // At/after expiry it is no longer a replay (and is GCed).
        assert!(!guard.is_replayed("S", STATE_TTL_MS + 1));
    }

    #[test]
    fn state_replay_guard_respects_cap() {
        let mut guard = StateReplayGuard::new();
        for i in 0..(MAX_USED_STATES + 10) {
            guard.mark_used(&format!("s{i:05}"), 0);
        }
        assert!(guard.used.len() <= MAX_USED_STATES);
    }

    #[test]
    fn classify_refresh_error_detects_invalid_grant() {
        assert_eq!(
            classify_refresh_error(r#"{"error":"invalid_grant"}"#),
            RefreshErrorKind::InvalidGrant
        );
        assert_eq!(
            classify_refresh_error(r#"{"error":"temporarily_unavailable"}"#),
            RefreshErrorKind::Other
        );
        assert_eq!(
            classify_refresh_error("503 Service Unavailable"),
            RefreshErrorKind::Other
        );
    }
}
