// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-destination liveness, surfaced so a half-dead multi-destination stream
 * (e.g. YouTube dropped but Facebook is fine) is VISIBLE instead of silently
 * hiding behind the tee's `onfail=ignore`. The list is in the same order as the
 * pushable destinations (= the tee slave order).
 */
export type DestinationHealth = { 
/**
 * User-facing name ("YouTube", "Kirkens server", …).
 */
name: string, 
/**
 * True while this destination is believed live; false once ffmpeg reported
 * its tee slave failed (reset to true on a full reconnect).
 */
ok: boolean, };
