// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FfmpegDevice } from "../../../../src/lib/bindings/FfmpegDevice";

/**
 * The capture devices ffmpeg can see, split by direction. Audio inputs feed the
 * recorder's mic match; video inputs feed the camera match.
 */
export type DeviceInventory = { 
/**
 * Microphones / line inputs ffmpeg enumerated (avfoundation index on macOS,
 * dshow name on Windows). The VU meter still uses the cpal list; these carry
 * the addressing the recorder needs. See module docs.
 */
audio_inputs: Array<FfmpegDevice>, 
/**
 * Cameras ffmpeg enumerated. Empty on audio-only setups.
 */
video_inputs: Array<FfmpegDevice>, };
