// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The result the renderer gets back: the report markdown, where it was saved
 * (if anywhere), and the tri-state capture results. Mirrors the non-secret
 * subset of the Electron `DiagnosticsReport`; `clipboardOk` is dropped because
 * the clipboard write is a UI-side concern (`navigator.clipboard`).
 */
export type DiagnosticsReport = { 
/**
 * The full markdown report (rendered by the panel + copied to clipboard).
 */
markdown: string, 
/**
 * Absolute path the report was written to, or `None` if the save failed.
 */
savedTo: string | null, 
/**
 * Audio capture test: `None` in F2.2 (deferred to Fase 3 — see module docs).
 */
captureOk: boolean | null, 
/**
 * Video capture test: `None` in F2.2 (deferred to Fase 3).
 */
videoOk: boolean | null, };
