// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the rendered preview mp3 landed (a temp file the renderer plays).
 */
export type EditorMasterPreviewResult = { previewPath: string, };
