// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A windowed mastering-preview request — render `[startSec, startSec+durationSec]`
 * of `inputPath` through the preset's single-pass chain to a temp mp3 the
 * renderer can `<audio>`-play A/B against the original. Mirrors `master-preview`.
 */
export type EditorMasterPreviewRequest = { inputPath: string, presetId: string, startSec: number, durationSec: number, };
