// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which sidecar a read/write/delete targets, mirroring the Electron suffixes.
 * Maps 1:1 to [`sundayrec_core::editor::Sidecar`].
 */
export type EditorSidecar = "meta" | "cutsDraft" | "transcript";
