// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A full two-pass mastering *apply* request — measure (pass 1, here re-measured
 * from the preset) then apply (pass 2) `inputPath` to `outputPath`, tracked by
 * `jobId` so the UI can [`master_cancel`] it. Mirrors `master-apply`.
 */
export type EditorMasterApplyRequest = { inputPath: string, outputPath: string, presetId: string, 
/**
 * Client-supplied job id for cancellation; the apply is rejected if it is
 * already in flight (duplicate-id guard, via the core JobRegistry).
 */
jobId: string, 
/**
 * Output bitrate (kbps) for lossy formats; `None` uses the codec default.
 */
bitrate: number | null, };
