// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorCutRegion } from "./EditorCutRegion";

/**
 * Export request — the cut-plan + a chosen format + optional mastering preset.
 * Mirrors the non-video subset of the Electron `EditorExportParams` the editor
 * UI sent (intro/outro/chapters/video are deferred — see module + docs).
 */
export type EditorExportRequest = { inputPath: string, cutRegions: Array<EditorCutRegion>, duration: number, 
/**
 * Output container: `mp3|aac|wav|flac|mp4`.
 */
format: string, 
/**
 * Folder to write into; the seam picks a collision-free name there.
 */
outputFolder: string, 
/**
 * Output bitrate (kbps) for lossy formats; `None` uses the codec default.
 */
bitrate: number | null, 
/**
 * WAV bit depth (16/24); ignored for non-WAV.
 */
bitDepth: number | null, 
/**
 * Optional mastering preset id (a two-pass loudnorm chain is applied first).
 */
masterPreset: string | null, 
/**
 * Optional intro clip prepended to the audio on export (non-mp4 only).
 */
introPath: string | null, 
/**
 * Optional outro clip appended to the audio on export (non-mp4 only).
 */
outroPath: string | null, };
