// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The result of probing a recording's streams for the editor — has_video /
 * has_audio so the renderer can choose the audio-only vs video editor layout.
 * Mirrors the Electron `editor-probe-streams` `MediaStreamInfo`.
 */
export type EditorStreamInfo = { hasVideo: boolean, hasAudio: boolean, };
