// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the email panel needs to render itself without a failed send: whether
 * this build compiled the `email` feature in at all, and whether a Gmail
 * refresh token is already stored (so the panel can offer the no-config path).
 * Filled by the `src-tauri` shell from the cargo feature + the keychain.
 */
export type EmailStatus = { 
/**
 * True when the binary was built with `--features email` (the send path is
 * present). The default build is `false` → the panel shows a calm hint.
 */
featureBuilt: boolean, 
/**
 * True when a Gmail OAuth refresh token is stored, so the Gmail transport
 * is usable without any SMTP fields.
 */
gmailConnected: boolean, };
