// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which transport the renderer asked the shell to use for a test send. Mirrors
 * `mailer.ts`'s "prefer Gmail OAuth, else SMTP" choice as an explicit pick the
 * user makes in the panel. Serialised lowercase on the wire.
 */
export type EmailTransportKind = "gmail" | "smtp";
