// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A missed scheduled recording, surfaced to the UI.
 */
export type MissedRecordingInfo = { 
/**
 * ISO-like local start time the recording was supposed to begin.
 */
at: string, 
/**
 * Human-readable label.
 */
label: string, };
