// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What feeds a lower-third overlay (the R3 subset).
 */
export type OverlaySource = { "kind": "image", path: string, } | { "kind": "text", title: string, subtitle: string | null, };
