// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Placement preset — the 9-grid + fullscreen + free positioning, mirroring the
 * Electron `OverlayPosition`.
 */
export type OverlayPosition = "tl" | "tc" | "tr" | "cl" | "c" | "cr" | "bl" | "bc" | "br" | "fullscreen" | "custom";
