// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverlayPosition } from "./OverlayPosition";
import type { OverlaySource } from "./OverlaySource";

/**
 * One overlay's configuration. Mirrors the non-capture subset of the Electron
 * `OverlayConfig`.
 */
export type OverlayConfig = { id: string, name: string, 
/**
 * Master on/off — disabled overlays are skipped in the graph.
 */
enabled: boolean, source: OverlaySource, position: OverlayPosition, 
/**
 * Only used when `position == Custom` — fractions of output WxH (0..1).
 */
customX: number | null, customY: number | null, 
/**
 * Overlay width as a fraction of output width (0..1); height auto-scales.
 * Forced to 1.0 for fullscreen. Default 0.3 when out of range.
 */
scale: number, 
/**
 * Final opacity 0..1 after any keying. Default 1.0.
 */
opacity: number, };
