// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The pre-roll status surfaced to the UI ("preroll aktiv").
 */
export type PrerollStatus = { 
/**
 * Whether the rolling capture loop is currently active.
 */
active: boolean, };
