// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A preview failure surfaced to the renderer over [`PREVIEW_ERROR_EVENT`]. The
 * `message` is already user-facing (Norwegian) so the UI can show it verbatim
 * instead of the silent dead-placeholder the old preview left behind.
 */
export type PreviewError = { 
/**
 * User-facing failure message.
 */
message: string, };
