// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecorderState } from "../../../../src/lib/bindings/RecorderState";

/**
 * The `recording://state` payload — the current [`RecorderState`] plus the
 * reconnect attempt count so the UI can show "reconnecting (3/20)".
 */
export type RecorderStatePayload = { 
/**
 * The lifecycle state.
 */
state: RecorderState, 
/**
 * How many reconnects have happened so far this session.
 */
reconnect_count: number, 
/**
 * Absolute epoch-ms the recording will auto-stop at, or `null` for no
 * auto-stop. Driven by `manual_max_minutes` at start; live extend/cancel
 * (`recording_extend_autostop` / `recording_cancel_autostop`) move or clear
 * it and the UI ticks a countdown to it locally.
 */
scheduled_stop_ms: number | null, };
