// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelMode } from "../../../../src/lib/bindings/ChannelMode";

/**
 * Options for [`RecorderEngine::start`].
 */
export type RecordingOpts = { 
/**
 * Stored microphone/mixer name to fuzzy-match against the enumerated audio
 * devices. Empty → first/default device.
 */
audio_device_name: string, 
/**
 * Stored camera name to match against video devices. `None` → audio-only.
 */
video_device_name: string | null, 
/**
 * Absolute output file path the (first) segment is written to.
 */
output_path: string, 
/**
 * User opted into stop-on-silence.
 */
stop_on_silence: boolean, 
/**
 * Silence threshold in dB (clamped by the core filter builder).
 */
silence_threshold_db: number | null, 
/**
 * Minutes of continuous silence before stop-on-silence fires (1–120).
 */
silence_timeout_minutes: number, 
/**
 * Capture framerate.
 */
framerate: number, 
/**
 * Output channel layout / downmix mode (stereo, mono-L, mono-R, mono-mix).
 */
channel_mode: ChannelMode, 
/**
 * Explicit 0-based device input channel → LEFT output (multi-channel mixers).
 * `None` keeps the `channel_mode` default routing.
 */
input_channel_l: number | null, 
/**
 * Explicit 0-based device input channel → RIGHT output. See `input_channel_l`.
 */
input_channel_r: number | null, 
/**
 * Capture sample rate in Hz, or `None` to capture at the device's NATIVE
 * rate (omit `-ar` — the anti-resample / anti-choppiness fix). Resolved from
 * `Settings::sample_rate_mode` via `resolved_sample_rate()`.
 */
sample_rate: number | null, 
/**
 * Output bitrate in kbps for lossy codecs (mp3/aac); ignored by wav/flac.
 */
bitrate_kbps: number, 
/**
 * Rotate to a fresh segment every N minutes (0 = off).
 */
split_minutes: number, 
/**
 * Auto-stop the whole session after N minutes (0 = off).
 */
manual_max_minutes: number, 
/**
 * Emit the live L/R level meters (`astats`) during capture? When `false`,
 * the levels filter is dropped to keep capture maximally stable.
 */
live_levels: boolean, 
/**
 * For a VIDEO recording, also extract a standalone audio sidecar file next to
 * the finished video. No-op for audio-only recordings (the main file already
 * is the audio).
 */
keep_separate_audio: boolean, 
/**
 * The extension/container for the separate audio sidecar (e.g. `"wav"`),
 * chosen from `Settings::separate_audio_format`. Drives the extract codec via
 * the shared `audio_encode_args` seam.
 */
separate_audio_format: string, 
/**
 * Capture resolution tag (`"480p"`/`"720p"`/`"1080p"`) from settings — the
 * camera-mode probe TARGET, so a 1080p setting records 1080p (when the camera
 * advertises it). Empty → 720p. Serialized (it roundtrips through the planner).
 */
video_resolution: string, };
