// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelMode } from "./ChannelMode";
import type { FileFormat } from "./FileFormat";
import type { FilenamePattern } from "./FilenamePattern";
import type { ScheduleSlot } from "./ScheduleSlot";
import type { SpecialRecording } from "./SpecialRecording";

/**
 * The complete (Fase-1 subset) settings model.
 *
 * Every field carries `#[serde(default)]` so a partial or older JSON blob
 * deserialises by filling in the per-field [`Default`] — this is the Electron
 * `store.get(key, default)` semantics, see [`Settings::from_json_merged`].
 * Numeric ranges are enforced separately by [`Settings::validate`].
 */
export type Settings = { 
/**
 * UI language code (e.g. `"no"`, `"en"`), or `None` to follow the OS.
 */
language: string | null, 
/**
 * Has the app ever been launched? Gates first-run behaviour.
 */
hasLaunched: boolean, 
/**
 * Has the user completed onboarding?
 */
onboardingDone: boolean, 
/**
 * Stored capture device id (browser `MediaDeviceInfo.deviceId` heritage).
 */
deviceId: string | null, 
/**
 * Stored capture device human-readable name (the device-match moat input).
 */
deviceName: string | null, 
/**
 * Capture video (camera) alongside audio? Default false (audio-only is the
 * common church-recording case).
 */
videoEnabled: boolean, 
/**
 * Stored camera human-readable name — the device-match moat input for video
 * (matched with [`crate::device_enum::find_best_video_device_match`]).
 */
videoDeviceName: string | null, 
/**
 * Last-known avfoundation index for the chosen camera. A fallback for when
 * the name lookup fails (e.g. after a reconnect); the name match wins when
 * it succeeds. dshow cameras are addressed by name, so this stays `None`.
 */
videoDeviceIndex: number | null, 
/**
 * Input channel layout.
 */
channels: ChannelMode, 
/**
 * Sample rate in Hz. Valid 8000..=192000, default 48000.
 */
sampleRate: number, 
/**
 * Input gain as a percentage. Valid 0..=200, default 100.
 */
inputVolume: number, 
/**
 * Bass EQ gain in dB. Valid -24..=24, default 0.
 */
eqBass: number, 
/**
 * Mid EQ gain in dB. Valid -24..=24, default 0.
 */
eqMid: number, 
/**
 * Treble EQ gain in dB. Valid -24..=24, default 0.
 */
eqTreble: number, 
/**
 * Is the compressor enabled?
 */
compEnabled: boolean, 
/**
 * Compressor threshold in dBFS. Valid -60..=0, default -24.
 */
compThreshold: number, 
/**
 * Compressor ratio. Valid 1..=100, default 4.
 */
compRatio: number, 
/**
 * Compressor attack in ms. Valid 0.1..=2000, default 10.
 */
compAttack: number, 
/**
 * Compressor release in ms. Valid 1..=9000, default 200.
 */
compRelease: number, 
/**
 * Is the limiter enabled? Default true.
 */
limiterEnabled: boolean, 
/**
 * Limiter ceiling in dBFS. Valid -10..=0, default -1.
 */
limiterCeiling: number, 
/**
 * Output file format. Default mp3.
 */
format: FileFormat, 
/**
 * Bitrate (kbps) as a string, matching the Electron `'192'` heritage.
 */
bitrate: string, 
/**
 * Filename generation pattern. Default `date`.
 */
filenamePattern: FilenamePattern, 
/**
 * Folder recordings are written to, or `None` for the default location.
 */
saveFolder: string | null, 
/**
 * Auto-delete recordings older than N days. Valid 0..=3650, 0 = off.
 */
autoDeleteDays: number, 
/**
 * Stop the recording after a sustained silent stretch?
 */
stopOnSilence: boolean, 
/**
 * Silence detection threshold in dBFS. Valid -90..=0, default -50.
 */
silenceThreshold: number, 
/**
 * Minutes of silence before auto-stop. Valid 1..=120, default 5.
 */
silenceTimeoutMinutes: number, 
/**
 * Auto-split interval in minutes. Valid 0..=480, 0 = off.
 */
splitMinutes: number, 
/**
 * Run ffmpeg `silenceremove` on the output (trim leading/trailing silence)?
 */
trimSilence: boolean, 
/**
 * Auto-stop manual recordings after N minutes. Valid 0..=1440, 0 = off.
 */
manualMaxMinutes: number, 
/**
 * Pre-roll buffer in seconds. Valid 0..=60, 0 = off.
 */
preRollSeconds: number, 
/**
 * Reminder notification N minutes before a scheduled recording.
 * Valid 0..=60, 0 = off.
 */
reminderMinutes: number, 
/**
 * Launch the app at OS login?
 */
launchAtLogin: boolean, 
/**
 * Show the window on startup (vs starting in the tray)?
 */
showOnStartup: boolean, 
/**
 * Minimise to the system tray instead of quitting? Default true.
 */
minimizeToTray: boolean, 
/**
 * Wake the machine from sleep for scheduled recordings? Default true.
 */
wakeFromSleep: boolean, 
/**
 * Require confirmation before stopping an in-progress recording? Default true.
 */
protectRecording: boolean, 
/**
 * Weekly recurring recording windows. Empty by default. The scheduler
 * engine turns these into start/stop/reminder/preflight timers; see
 * [`crate::schedule`] for the decision logic.
 */
slots: Array<ScheduleSlot>, 
/**
 * One-off dated recordings (concerts, special services). Empty by default.
 * Auto-pruned 7 days after they end ([`crate::schedule::prune_specials`]).
 */
specialRecordings: Array<SpecialRecording>, 
/**
 * Download and install updates automatically? Default true.
 */
autoUpdate: boolean, 
/**
 * Prompt to open the editor after a recording finishes? Default true.
 */
askOpenEditor: boolean, };
