// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A stream destination as the renderer holds it — the key is NOT carried here;
 * it lives in the keychain and is resolved by id at start. `hasKey` mirrors the
 * Electron `StreamDestinationStored.hasKey` so the UI shows "•••• (saved)".
 */
export type StreamDestinationView = { id: string, name: string, rtmpUrl: string, enabled: boolean, hasKey: boolean, };
