// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DestinationHealth } from "./DestinationHealth";

/**
 * Live stream status surfaced to the renderer. Mirrors the Electron
 * `StreamStats` (sans the per-line churn). `active` is the single source of
 * truth for the start/stop button.
 */
export type StreamStatus = { active: boolean, 
/**
 * Epoch-ms when the current stream started, or `None`.
 */
startedAt: bigint | null, 
/**
 * Most recent total bitrate (kbps).
 */
bitrateKbps: number, 
/**
 * Most recent encoder FPS.
 */
fps: number, 
/**
 * Frames dropped so far.
 */
dropped: number, 
/**
 * Last interesting stderr line (e.g. a connection error), key-redacted.
 */
lastLine: string, 
/**
 * Per-destination liveness, in pushable order. Empty when idle.
 */
destinations: Array<DestinationHealth>, };
