// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StreamDestination } from "./StreamDestination";
import type { StreamResolution } from "./StreamResolution";

/**
 * Full set of options for one stream launch. The renderer-facing mirror of the
 * Electron `StreamOptions` (overlays are threaded in separately by the seam via
 * [`crate::overlay`]).
 */
export type StreamOptions = { resolution: StreamResolution, 
/**
 * Frames per second — 25 or 30 in the Electron app; the GOP is `fps × 2`.
 */
framerate: number, 
/**
 * Video bitrate (kbps); `None` → the resolution's `auto_bitrate_kbps`.
 */
videoBitrateKbps: number | null, 
/**
 * Audio bitrate (kbps); `None` → 128.
 */
audioBitrateKbps: number | null, 
/**
 * Push targets. Non-pushable ones are skipped.
 */
destinations: Array<StreamDestination>, 
/**
 * Optional local MP4 written by the same pipeline (the "stream + opptak"
 * pattern). `None` → no local copy. The bitrate defaults to `video × 1.6`.
 */
alsoRecordPath: string | null, };
