// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One RTMP push target. The `stream_key` is sensitive — it's joined into the
 * URL only inside [`joined_rtmp_url`] and never appears in [`StreamArgs::loggable`].
 */
export type StreamDestination = { 
/**
 * Stable id for UI tracking + key storage.
 */
id: string, 
/**
 * User-facing name ("YouTube", "Kirkens server", …).
 */
name: string, 
/**
 * RTMP base URL, no stream key. Example: `rtmp://a.rtmp.youtube.com/live2`.
 */
rtmpUrl: string, 
/**
 * Stream key — sensitive, resolved from the vault by the caller.
 */
streamKey: string, 
/**
 * Skip this destination without deleting it.
 */
enabled: boolean, };
