// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why building the output args failed before any spawn. Stable for the renderer.
 */
export type StreamArgError = "no_destinations";
