// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TestRecordingError } from "./TestRecordingError";
import type { TestRecordingSignal } from "./TestRecordingSignal";

/**
 * The result of a test recording. Mirrors the Electron `TestRecordingResult`
 * (camelCase): on success, the captured file's size + measured signal; on
 * failure, the classified error kind.
 */
export type TestRecordingResult = { 
/**
 * Whether the test produced a plausible recording.
 */
ok: boolean, 
/**
 * The classified failure, when `ok == false`.
 */
error: TestRecordingError | null, 
/**
 * Output file size in bytes, when a file was produced.
 */
sizeBytes: number | null, 
/**
 * Measured signal strength, on success.
 */
signal: TestRecordingSignal | null, };
