// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A subtitle/text format the transcript can be exported to. Serialised
 * lowercase to match the file extension (`srt` | `vtt` | `txt`).
 */
export type TranscriptExportFormat = "srt" | "vtt" | "txt";
