// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The current state of an update check/download, as the renderer renders it.
 *
 * Mirrors the Electron `update-*` IPC events one-to-one. `Idle` is the
 * pre-check resting state (the renderer shows the "click to check" hint);
 * every other variant maps to an `update.<key>` i18n string.
 */
export type UpdateStatus = { "phase": "idle" } | { "phase": "checking" } | { "phase": "upToDate" } | { "phase": "available", version: string, } | { "phase": "downloading", version: string, percent: number, } | { "phase": "readyToInstall", version: string, } | { "phase": "error", message: string, };
