// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioDevice } from "./AudioDevice";

/**
 * The result of enumerating the system's input devices.
 */
export type AudioDeviceList = { 
/**
 * The cpal host backing this enumeration (e.g. `"CoreAudio"`, `"WASAPI"`).
 */
host: string, 
/**
 * Available input (microphone) devices.
 */
inputs: Array<AudioDevice>, };
