// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The shaped result of the settings "diagnose audio" probe (mirrors the Electron
 * `diagnose-audio` handler in `src/main/ipc/audio-devices.ts`). The renderer
 * renders one populated dropdown from this in a single round-trip.
 *
 * `dshow` carries the DirectShow/avfoundation audio-input names, `wasapi` the
 * WASAPI loopback names (empty off Windows), and `wasapi_available` whether the
 * loopback bridge is usable on this host. The shaping is pure — turning parsed
 * [`FfmpegDevice`] lists into the flat name lists the panel wants — so it is
 * unit-tested without spawning ffmpeg.
 */
export type AudioDiagnostics = { 
/**
 * DirectShow (Windows) / avfoundation (macOS) audio-input device names.
 */
dshow: Array<string>, 
/**
 * WASAPI loopback device names (empty off Windows).
 */
wasapi: Array<string>, 
/**
 * Whether the WASAPI loopback bridge is available on this host.
 */
wasapiAvailable: boolean, };
