// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Authorization status, mirroring Apple's `AVAuthorizationStatus`.
 */
export type AuthStatus = "notDetermined" | "restricted" | "denied" | "authorized" | "unknown";
