// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a camera can actually capture, for gating the resolution/fps UI to modes
 * the device advertises (mirror of [`sundayrec_core::capture::CameraCapabilities`]).
 */
export type CameraCapabilities = { maxWidth: number, maxHeight: number, maxFps: number, supportedResolutions: Array<string>, supportedFramerates: Array<number>, };
