// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input channel layout. Serialised to the EXACT Electron string union
 * (`'stereo' | 'monoL' | 'monoR' | 'monoMix'`, see `types/index.ts:1`), so the
 * tags are camelCase — NOT snake_case — to match stored/exported settings.
 */
export type ChannelMode = "stereo" | "monoL" | "monoR" | "monoMix";
