// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A chapter marker on a recording. Mirrors the renderer `ChapterMarker`:
 * `time` in seconds from the start of the main content.
 */
export type ChapterMarker = { time: number, title: string, };
