// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A cloud service the user can connect via OAuth. Serialised kebab-case to
 * match the Electron `TokenServiceId` strings exactly (`'google-drive'`,
 * `'youtube'`, `'gmail'`) so saved tokens and log shapes carry across the
 * migration. All three share a single Google OAuth client (different scopes);
 * each is stored under its own key so a user can connect Drive without
 * granting YouTube, etc. (`config.ts:40`, `token-store.ts:5`).
 */
export type CloudService = "google-drive" | "youtube" | "gmail";
