// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloudService } from "./CloudService";

/**
 * Whether a cloud service currently holds a stored refresh token. UI-facing
 * status the `src-tauri` shell fills from the keychain (Fase 6). Defined here,
 * next to [`CloudService`], so the generated TS binding resolves cleanly.
 */
export type CloudConnectionStatus = { service: CloudService, connected: boolean, };
