// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A backup-destination folder the user picked. Mirrors the Electron token's
 * `{ folderId, folderName, folderPath? }`. Persisted as a JSON setting so it
 * survives restarts (the Tauri token vault holds only the refresh token).
 */
export type CloudFolder = { folderId: string, folderName: string, folderPath: string | null, };
