// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingsSummary } from "./SettingsSummary";

/**
 * Everything the `src-tauri` layer gathered, ready to be formatted. No secrets
 * can appear here (see [`SettingsSummary`] / module docs).
 */
export type DiagnosticsInput = { 
/**
 * App semver (e.g. `"0.1.0"`).
 */
appVersion: string, 
/**
 * Target OS (`std::env::consts::OS` — `"macos"`, `"windows"`, …).
 */
platform: string, 
/**
 * CPU architecture (`std::env::consts::ARCH`).
 */
arch: string, 
/**
 * First line of `ffmpeg -version`, or `None` when ffmpeg did not resolve.
 */
ffmpegVersion: string | null, 
/**
 * Audio capture device names ffmpeg / cpal enumerated.
 */
audioDevices: Array<string>, 
/**
 * Video capture device names ffmpeg enumerated.
 */
videoDevices: Array<string>, 
/**
 * The non-secret settings summary.
 */
settings: SettingsSummary, 
/**
 * Audio capture test result: `Some(true)`=ok, `Some(false)`=failed,
 * `None`=not tested (the F2.2 default — the live test is Fase-3 hardware).
 */
captureOk: boolean | null, 
/**
 * Video capture test result, same tri-state. `None` when not tested /
 * video disabled.
 */
videoOk: boolean | null, };
