// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Free bytes on the volume holding the save folder, or `null` when the platform
 * can't report it. Mirrors the Electron `get-disk-space` handler, but uses the
 * `fs4` cross-platform probe (already a dep, used by preflight) instead of
 * shelling out to `df`/`powershell`. Fully testable — no device, no ffmpeg.
 */
export type DiskSpace = { 
/**
 * Free space in bytes, or `null` when unavailable.
 */
freeBytes: number | null, };
