// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Drive folder the user can pick as a backup destination. Mirrors the
 * Electron `listFolders` `{ id, name }` shape.
 */
export type DriveFolder = { id: string, name: string, };
