// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One content-detected segment for the editor timeline. Reuses the core
 * `SegmentType` lowercase strings (or `"sermon"` for the promoted block), the
 * same shape `detectSegments` returned to the Electron renderer.
 */
export type EditorSegment = { start: number, end: number, duration: number, label: string, 
/**
 * `silence|speech|music|mixed|unknown|sermon`.
 */
kind: string, };
