// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One parametric EQ band (mirror of [`sundayrec_core::processing::EqBand`]).
 */
export type EditorEqBand = { freqHz: number, gainDb: number, q: number, };
