// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorChannelRepair } from "./EditorChannelRepair";

/**
 * The result of analysing a recording's stereo channel balance (mirror of
 * [`sundayrec_core::processing::ChannelDiagnosis`] plus the measured peaks and a
 * ready-to-apply [`EditorChannelRepair`]).
 */
export type EditorChannelDiagnosis = { 
/**
 * `balanced|imbalance|dead_left|dead_right|both_dead|mono`.
 */
code: string, 
/**
 * Left − right level difference in dB (positive = left louder).
 */
imbalanceDb: number, peakLeftDb: number, peakRightDb: number | null, 
/**
 * The repair to apply (`mode == "none"` when nothing is recommended).
 */
recommended: EditorChannelRepair, };
