// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The measured loudness the mastering UI shows before/after a preset, mirroring
 * the pass-1 `loudnorm` JSON the Electron mastering flow surfaced.
 */
export type EditorLoudness = { 
/**
 * Measured integrated loudness (LUFS).
 */
inputI: number, 
/**
 * Loudness range.
 */
inputLra: number, 
/**
 * True peak (dBTP).
 */
inputTp: number, 
/**
 * The preset this was measured against (its target LUFS for the delta UI).
 */
targetLufs: number, };
