// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A mastering-apply progress tick, emitted on the `editor-master-progress`
 * event. Mirrors the Electron `master-progress` `{ currentSec, totalSec }`.
 */
export type EditorMasterProgress = { jobId: string, currentSec: number, totalSec: number, };
