// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One timestamped transcript line fed to chapter detection. Mirrors the whisper
 * `TranscriptSegment` subset the detector needs (start + text).
 */
export type EditorTranscriptLine = { start: number, text: string, };
