// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How to repair the channel layout (mirror of
 * [`sundayrec_core::processing::ChannelRepair`]). `mode` is one of
 * `none|swapLr|duplicateLeft|duplicateRight|monoMix|gainDb`; `leftDb`/`rightDb`
 * are only read for `gainDb`.
 */
export type EditorChannelRepair = { mode: string, leftDb: number, rightDb: number, };
