// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The outcome of an export: where the file landed.
 */
export type EditorExportResult = { outputPath: string, };
