// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorChapter } from "./EditorChapter";
import type { EditorCutRegion } from "./EditorCutRegion";

/**
 * Export request — the cut-plan + a chosen format + optional mastering preset,
 * intro/outro jingles, and topic chapters. Mirrors the non-video subset of the
 * Electron `EditorExportParams` the editor UI sent (mp4 video re-encode aside).
 */
export type EditorExportRequest = { inputPath: string, cutRegions: Array<EditorCutRegion>, duration: number, 
/**
 * Output container: `mp3|aac|wav|flac|mp4`.
 */
format: string, 
/**
 * Folder to write into; the seam picks a collision-free name there.
 */
outputFolder: string, 
/**
 * Output bitrate (kbps) for lossy formats; `None` uses the codec default.
 */
bitrate: number | null, 
/**
 * WAV bit depth (16/24); ignored for non-WAV.
 */
bitDepth: number | null, 
/**
 * Optional mastering preset id (a two-pass loudnorm chain is applied first).
 */
masterPreset: string | null, 
/**
 * Optional intro clip prepended to the audio on export (non-mp4 only).
 */
introPath: string | null, 
/**
 * Optional outro clip appended to the audio on export (non-mp4 only).
 */
outroPath: string | null, 
/**
 * Optional peak-normalization gain (dB) applied as a `volume` filter — what
 * the editor's "Normalize" button computes. `None`/`0` is a no-op.
 */
gainDb: number | null, 
/**
 * Topic chapters to embed in the exported file (FFMETADATA → ID3 CHAP/CTOC).
 * Times are in the ORIGINAL recording timeline; export remaps them through
 * the cut-plan and drops any that fall inside a cut. Empty = none embedded.
 */
chapters: Array<EditorChapter>, 
/**
 * Optional file title (FFMETADATA `title`); also used as the chapter header.
 */
title: string | null, 
/**
 * Optional speaker (FFMETADATA `artist`).
 */
speaker: string | null, 
/**
 * Optional description (FFMETADATA `comment`).
 */
description: string | null, };
