// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One chapter marker (a title at a time, in seconds). The renderer-facing mirror
 * of [`sundayrec_core::editor::Chapter`].
 */
export type EditorChapter = { time: number, title: string, };
