// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `editor-read-file` outcome: either the file is small enough to read its
 * bytes inline, or it is over the 400 MB limit and the renderer must stream it
 * via the peaks-extract path. Mirrors the `{ tooLarge, size }` shape.
 */
export type EditorFileRead = { 
/**
 * Over the inline limit — the renderer should stream instead.
 */
tooLarge: boolean, 
/**
 * The file's size in bytes (always reported).
 */
size: bigint, 
/**
 * The bytes, present only when within the inline limit.
 */
bytes: Array<number> | null, };
