// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorChannelRepair } from "./EditorChannelRepair";
import type { EditorEqBand } from "./EditorEqBand";

/**
 * The full, per-stage vocal-chain configuration (mirror of
 * [`sundayrec_core::processing::VocalChain`]). Every stage is independently
 * toggleable; `serde(default)` lets the renderer send a partial object. When an
 * export carries this it overrides any `vocalChainPreset`.
 */
export type EditorProcessing = { channelRepair: EditorChannelRepair | null, highpassEnabled: boolean, highpassHz: number, denoiseEnabled: boolean, denoiseDb: number, denoiseFloorDb: number, dereverbEnabled: boolean, dereverbStrength: number, gateEnabled: boolean, gateThresholdDb: number, gateRatio: number, eq: Array<EditorEqBand>, compEnabled: boolean, compThresholdDb: number, compRatio: number, compAttackMs: number, compReleaseMs: number, compMakeupDb: number, deesserEnabled: boolean, deesserIntensity: number, limiterEnabled: boolean, limiterDb: number, gainDb: number, };
