// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A cut region (seconds) the renderer marked to remove. Mirrors the Electron
 * `CutRegion`; converted to [`sundayrec_core::editor::CutRegion`] in the seam.
 */
export type EditorCutRegion = { start: number, end: number, };
