// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The waveform peaks the renderer draws, plus the authoritative duration
 * (ffprobe's, not the renderer's `<audio>.duration` which can lie on VBR).
 */
export type EditorPeaks = { 
/**
 * Max-abs amplitude per bucket, 0..1, length ≤ `PEAK_BUCKETS`.
 */
peaks: Array<number>, 
/**
 * The sample rate the peaks were decoded at (8 kHz — see core).
 */
sampleRate: number, };
