// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A mastering preset for the editor's preset dropdown (mirror of
 * [`sundayrec_core::mastering::MasterPreset`]). The renderer renders `label`/
 * `description` and applies by `id`.
 */
export type EditorMasterPreset = { id: string, label: string, description: string, targetLufs: number, targetLra: number, truePeakDb: number, filters: string, };
