// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a load-probe resolved about a recording, for the editor's first paint.
 * The renderer-facing mirror of [`sundayrec_core::editor::ProbeResult`].
 */
export type EditorMediaInfo = { durationSec: number, hasVideo: boolean, hasAudio: boolean, channels: number | null, sampleFmt: string | null, };
