// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EpisodePrepStatus } from "./EpisodePrepStatus";
import type { PrepAnalysisSegment } from "./PrepAnalysisSegment";
import type { SuggestedTrim } from "./SuggestedTrim";

/**
 * A publish-ready episode candidate awaiting human review. Mirrors the renderer
 * `EpisodePrep` (camelCase) so it round-trips to the UI unchanged.
 */
export type EpisodePrep = { id: string, recordingPath: string, timestamp: number, status: EpisodePrepStatus, analysisSegments: Array<PrepAnalysisSegment>, suggestedTrim: SuggestedTrim | null, sermonConfidence: number | null, masterPreset: string, introPath: string | null, outroPath: string | null, attentionReasons: Array<string> | null, createdAt: number, updatedAt: number, };
