// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of an `EpisodePrep`. Mirrors the renderer `EpisodePrepStatus`
 * (kebab-case strings).
 */
export type EpisodePrepStatus = "analyzing" | "ready" | "needs-attention" | "published" | "discarded";
