// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The result of a feed preview/generate: the rendered XML (preview) or the
 * written path (generate), plus the episode count.
 */
export type FeedPreview = { 
/**
 * The rendered feed XML.
 */
xml: string, 
/**
 * How many episodes the feed contains.
 */
episodeCount: number, 
/**
 * Where the feed was written on disk, if `publish_generate_feed` wrote it.
 */
localPath: string | null, 
/**
 * The public feed URL once uploaded + shared (None until the Drive glue lands).
 */
feedUrl: string | null, };
