// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of probing the bundled ffmpeg — surfaced in the diagnostics UI so the
 * user (and we, during development) can confirm the sidecar resolved.
 */
export type FfmpegHealth = { 
/**
 * Whether `ffmpeg -version` ran successfully.
 */
available: boolean, 
/**
 * The first line of `ffmpeg -version` (the build banner), when available.
 */
version: string | null, 
/**
 * The resolved path we tried to run (env override / sidecar / PATH name).
 */
path: string, };
