// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A capture device as enumerated from ffmpeg's device listing. Minimal on
 * purpose — matching only needs the human-readable `name`; `format`
 * (`"avfoundation"` / `"dshow"`) and the optional avfoundation `index` are
 * carried so the caller can build input args without a second lookup.
 */
export type FfmpegDevice = { 
/**
 * Human-readable device name as ffmpeg reports it.
 */
name: string, 
/**
 * Capture format this device belongs to (`"avfoundation"`, `"dshow"`, …).
 */
format: string, 
/**
 * avfoundation device index (`Some(0)`, `Some(1)`, …) when known. dshow
 * devices are addressed by name, so this is `None` there.
 */
index: number | null, };
