// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output audio container/codec. Serialised lowercase to match the Electron
 * union (`'mp3' | 'wav' | 'flac' | 'aac'`, see `types/index.ts:2`).
 */
export type FileFormat = "mp3" | "wav" | "flac" | "aac";
