// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How recording filenames are generated. Serialised lowercase to match the
 * Electron union (`'date' | 'church' | 'plain' | 'datetime'`,
 * see `types/index.ts:3`).
 */
export type FilenamePattern = "date" | "church" | "plain" | "datetime";
