// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The opt-in connection details shared by the Song/Plan flows + the live bridge.
 * Mirrors `IntegrationSettings.connection` (camelCase). No secrets here.
 */
export type IntegrationConnection = { churchId?: string | null, serviceId?: string | null, songApiUrl?: string | null, planApiUrl?: string | null, };
