// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IntegrationConnection } from "./IntegrationConnection";
import type { PeerToggle } from "./PeerToggle";

/**
 * The full opt-in integration settings bag. Mirrors `IntegrationSettings`
 * field-for-field (camelCase). `enabled` is the master opt-in for the area.
 */
export type IntegrationSettings = { enabled: boolean, verbatim?: PeerToggle | null, stage?: PeerToggle | null, song?: PeerToggle | null, plan?: PeerToggle | null, connection?: IntegrationConnection | null, };
