// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One liturgical day in a month: its ISO date (`YYYY-MM-DD`) and the Norwegian
 * feast name from [`sundayrec_core::church_calendar::liturgical_day_name`].
 */
export type LiturgicalDay = { 
/**
 * ISO date, `YYYY-MM-DD`.
 */
date: string, 
/**
 * Norwegian liturgical day name (e.g. `"1. påskedag"`).
 */
name: string, };
