// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthStatus } from "./AuthStatus";

/**
 * The current camera + microphone authorization, for the UI / preflight.
 */
export type MediaPermissions = { camera: AuthStatus, microphone: AuthStatus, };
