// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress event for a model download. Mirrors `whisper-models.ts`
 * `ModelDownloadProgress` (camelCase on the wire) so the renderer's progress
 * bar reads the same fields it did under Electron.
 */
export type ModelDownloadProgress = { 
/**
 * The model id this progress belongs to.
 */
id: string, 
/**
 * Bytes received so far.
 */
bytesDownloaded: number, 
/**
 * Total expected bytes (the `content-length`, falling back to the registry
 * `size_bytes`).
 */
bytesTotal: number, 
/**
 * Completion fraction in `0.0..=1.0`, or `None` when the total is unknown.
 */
fraction: number | null, };
