// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NdiPixFmt } from "./NdiPixFmt";

/**
 * Options for advertising SundayRec's program feed as an NDI output. The
 * renderer-facing mirror surfaced to the UI; the `src-tauri` seam consumes it
 * to build the ffmpeg output args (once an NDI-capable ffmpeg is present).
 */
export type NdiOutputOptions = { 
/**
 * The advertised source name other machines discover. Validate with
 * [`validate_ndi_source_name`] before use.
 */
sourceName: string, 
/**
 * The pixel format frames are transmitted in. `uyvy422` is the standard,
 * bandwidth-friendly 4:2:2 NDI format; `bgra` carries alpha (rarely needed
 * for a program feed).
 */
pixFmt: NdiPixFmt, };
