// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The ffmpeg rawvideo pixel format we read NDI frames as. UYVY is the smaller,
 * no-alpha 4:2:2 format; BGRA carries the alpha channel (for chroma/alpha-key
 * compositing). Mirrors the Electron `'uyvy422' | 'bgra'`.
 */
export type NdiPixFmt = "uyvy422" | "bgra";
