// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NdiPixFmt } from "./NdiPixFmt";

/**
 * A receiver resolved enough to wire ffmpeg: the loopback port it serves on,
 * the pixel format, the frame size (from the first frame), and the framerate.
 * The renderer-facing mirror of the Electron `ReceiverHandle`'s data fields.
 */
export type NdiReceiverInfo = { 
/**
 * Loopback TCP port ffmpeg connects to.
 */
port: number, pixFmt: NdiPixFmt, width: number, height: number, 
/**
 * Best-effort framerate (libndi reports, or a 30 fallback the seam sets).
 */
framerate: number, };
