// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why an NDI source name was rejected. Stable (snake_case) so the renderer can
 * map to a localized message without parsing free text — mirrors the
 * [`crate::streaming::StreamKeyError`] idiom.
 */
export type NdiSourceNameError = "empty" | "too_long" | "has_control_char";
