// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A source advertising on the network, as surfaced to the UI. Mirrors the
 * Electron `NdiSourceInfo`.
 */
export type NdiSource = { 
/**
 * Full advertised name, e.g. `"STUDIO-PC (ProPresenter Output 1)"`.
 */
name: string, 
/**
 * Resolvable `IP:port` (or a LOCAL HOST marker for same-machine sources).
 */
address: string, };
