// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One OS-observed wake, for the verification panel.
 */
export type ObservedWake = { scheduledAt: string, ownerLabel: string, };
