// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single peer-app toggle. Mirrors the Electron `{ enabled: boolean }` peers.
 */
export type PeerToggle = { enabled: boolean, };
