// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The speaker assignment on a sermon item.
 */
export type PlanAssignment = { speaker?: string | null, };
