// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanServiceItem } from "./PlanServiceItem";

/**
 * A planned service from SundayPlan. Mirrors the Electron `PlanService`.
 */
export type PlanService = { id: string, name: string, starts_at_utc: string, state: string, was_streamed_flag?: boolean | null, items?: Array<PlanServiceItem> | null, };
