// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanAssignment } from "./PlanAssignment";

/**
 * A planned service item (song / sermon / scripture …). Mirrors the Electron
 * `PlanServiceItem` (snake_case from the Supabase REST shape).
 */
export type PlanServiceItem = { id: string, kind: string, label?: string | null, assignment?: PlanAssignment | null, };
