// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A derived schedule slot. Mirrors `serviceToSchedule`'s return shape.
 */
export type PlanSchedule = { date: string, startTime: string, stopTime: string, note: string, };
