// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Derived recording metadata. Mirrors `serviceToMetadata`'s return shape.
 */
export type PlanMetadata = { title: string, speaker: string, };
