// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Capture host platform. We only branch on it where the underlying OS audio
 * stack actually forces a difference.
 */
export type Platform = "macos" | "windows" | "linux";
