// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreflightCategory } from "./PreflightCategory";
import type { PreflightSeverity } from "./PreflightSeverity";

/**
 * A single thing the preflight check found. Mirrors the Electron
 * `PreflightFinding` interface field-for-field.
 */
export type PreflightFinding = { severity: PreflightSeverity, category: PreflightCategory, message: string, };
