// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How serious a finding is. Serialised lowercase to match the Electron
 * `'warn' | 'error'` union (`preflight.ts:21`).
 */
export type PreflightSeverity = "warn" | "error";
