// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SegmentType } from "./SegmentType";

/**
 * One analysis segment. Mirrors the renderer `PrepAnalysisSegment` (camelCase),
 * which is itself the renderer-facing mirror of `audio-analysis.ts`
 * `AnalysisSegment`. Fed in by the shell; this module never computes it.
 */
export type PrepAnalysisSegment = { startSec: number, endSec: number, durationSec: number, type: SegmentType, confidence: number, avgRmsDb: number, label: string, };
