// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A harvested, trimmed pre-roll clip ready to prepend to a recording.
 *
 * `raw_path` is the *trimmed* AAC `.m4a` produced by [`PrerollEngine::harvest`]
 * (not the raw WAV — that is consumed + deleted during harvest). `trim_ms` and
 * `start_offset_ms` are the core mat's verdict, kept on the clip for diagnostics
 * and for the future concat step.
 */
export type PrerollClip = { 
/**
 * Absolute path to the trimmed `.m4a` clip.
 */
raw_path: string, 
/**
 * Milliseconds of audio kept (the prepend length).
 */
trim_ms: number, 
/**
 * Where in the raw capture the kept window started (ffmpeg `-ss`), for
 * diagnostics; the trimmed clip already begins here.
 */
start_offset_ms: number, };
