// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One preview frame delivered to the renderer. `data` is a base64-encoded JPEG
 * (drop it straight into `src="data:image/jpeg;base64,…"`).
 *
 * base64 roughly +33% over the raw bytes; acceptable for a low-fps preview, and
 * it keeps the payload plain JSON. A raw-binary channel is a later optimisation
 * if the preview rate ever climbs.
 */
export type PreviewFrame = { 
/**
 * Base64-encoded JPEG bytes (no data-URL prefix).
 */
data: string, 
/**
 * Frame width in pixels, when the JPEG header could be parsed.
 */
width: number | null, 
/**
 * Frame height in pixels, when the JPEG header could be parsed.
 */
height: number | null, 
/**
 * Monotonic frame counter since this preview session started (1-based).
 */
seq: number, };
