// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether this build can write/upload the feed, plus the candidate episode count
 * (every recording in history — the placeholder preview keeps them all). Works in
 * every build: `feature_built` reflects the compile-time `publish` feature.
 */
export type PublishStatus = { 
/**
 * True when this build was compiled with `--features publish` (can write/upload).
 */
featureBuilt: boolean, 
/**
 * How many recordings would appear in the feed (all of history, newest-first).
 */
episodeCount: number, };
