// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloudService } from "./CloudService";
import type { UploadStatus } from "./UploadStatus";

/**
 * One file queued for cloud upload. Mirrors the Electron `CloudUploadQueueEntry`
 * field-for-field (camelCase on the wire via the struct-level rename) so the
 * renderer and any persisted rows carry across unchanged.
 */
export type QueueEntry = { id: string, service: CloudService, filePath: string, 
/**
 * History-entry timestamp to mark uploaded on success (`entryTimestamp`).
 */
entryTimestamp: number | null, attempts: number, 
/**
 * Unix ms — earliest time the worker may try this entry.
 */
nextAttempt: number, lastError: string | null, enqueuedAt: number, status: UploadStatus, };
