// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloudService } from "./CloudService";
import type { UploadStatus } from "./UploadStatus";

/**
 * A compact, UI-facing view of one entry (`getQueueStatus` maps to this:
 * filename only, no full path). `filename` is the basename of `file_path`.
 */
export type QueueEntryView = { id: string, service: CloudService, filename: string, attempts: number, nextAttempt: number, lastError: string | null, status: UploadStatus, };
