// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A progress heartbeat sent to the renderer.
 */
export type RecordingProgress = { 
/**
 * Total bytes ffmpeg has written to the current segment so far.
 */
bytes_written: number, };
