// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable error codes the recorder watchdog and the UI localisation switch on.
 *
 * Serialised in `snake_case` to match the Electron string union
 * (`device_not_found`, `device_permission_denied`, …) so existing
 * expectations and any persisted data line up.
 */
export type RecordingErrorCode = "device_not_found" | "device_permission_denied" | "device_busy" | "disk_full" | "device_disconnected" | "device_error";
