// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Live per-channel peak audio levels (dBFS) sent to the renderer, parsed from
 * the recorder's own ffmpeg `astats` telemetry. Drives the L/R meters in the
 * "Opptaksmodus" overlay. `peak_db_right` is `None` for mono sources.
 *
 * Field names mirror [`RecordingProgress`] (no serde rename) → the generated TS
 * binding is `peak_db_left` / `peak_db_right`.
 */
export type RecordingLevels = { 
/**
 * Peak level (dBFS) of the left / only channel.
 */
peak_db_left: number, 
/**
 * Peak level (dBFS) of the right channel, or `null` for mono sources.
 */
peak_db_right: number | null, };
