// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A classified recorder error / silence / reconnect notice sent to the renderer.
 */
export type RecordingEvent = { 
/**
 * Stable code the UI localises (snake_case, e.g. `device_disconnected`,
 * `stuck_recording`, `silence_detected`).
 */
code: string, 
/**
 * Human-readable detail for logs / a diagnostics surface.
 */
message: string, };
