// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for [`FINISHED_EVENT`] — where the finished recording landed, so the
 * UI's "open in editor" action can load it straight into the editor.
 */
export type RecordingFinished = { 
/**
 * Absolute path to the finished recording file.
 */
file_path: string, 
/**
 * Whether it is a video (mp4) recording.
 */
has_video: boolean, };
