// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The recorder lifecycle, surfaced to the UI as a `recording://state` event.
 *
 * Serialised `snake_case` to match the renderer's localisation switch.
 */
export type RecorderState = "idle" | "preparing" | "recording" | "reconnecting" | "stopping" | "stopped" | "failed";
