// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EpisodePrep } from "./EpisodePrep";

/**
 * One queue entry: an [`EpisodePrep`] plus bookkeeping. Mirrors the renderer
 * `ReviewQueueEntry` (camelCase). `age_in_days` is derived on read, not stored.
 */
export type ReviewQueueEntry = { id: string, prep: EpisodePrep, addedAt: number, 
/**
 * Reminders sent so far: 0=none, 1=24h, 2=48h, 3=7d.
 */
reminded: number, 
/**
 * Days since `added_at` — computed on read (0 when persisted).
 */
ageInDays: number, };
