// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Capture sample-rate policy. `Auto` (the default) captures at the device's
 * NATIVE rate — the recorder omits `-ar` entirely so ffmpeg never resamples
 * (forcing a 48 kHz `-ar` on a 44.1 kHz USB mixer dropped samples → choppy
 * audio). The explicit rates force that rate via `-ar`. Serialised camelCase
 * (`"auto" | "r44100" | "r48000" | "r96000"`).
 */
export type SampleRate = "auto" | "r44100" | "r48000" | "r96000";
