// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A weekly recurring recording window. Mirrors the Electron `ScheduleSlot`
 * (`types/index.ts:18`): `{ days: number[]; start: string; stop: string; max?: number }`.
 */
export type ScheduleSlot = { 
/**
 * Active weekdays, 0 = Monday … 6 = Sunday.
 */
days: Array<number>, 
/**
 * Start time `HH:MM` (local wall clock).
 */
start: string, 
/**
 * Stop time `HH:MM` (local wall clock). May be < start (crosses midnight).
 */
stop: string, 
/**
 * Optional hard cap in minutes for this slot's recording length.
 */
max: number | null, };
