// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The scheduler snapshot the UI renders: the next start and the next 14 days
 * of starts (ISO-like local strings).
 */
export type ScheduleStatus = { next: string | null, upcoming: Array<string>, };
