// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of an analysis segment. Serialised lowercase to match the Electron
 * `SegmentType` strings (`'silence' | 'speech' | 'music' | 'mixed' | 'unknown'`).
 */
export type SegmentType = "silence" | "speech" | "music" | "mixed" | "unknown";
