// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceLinkSource } from "./ServiceLinkSource";
import type { SongUsage } from "./SongUsage";

/**
 * Links one recording to its external service context. Persisted as a
 * `<recording>.service.json` sidecar by the shell. Mirrors the renderer
 * `ServiceLink` (camelCase).
 */
export type ServiceLink = { source: ServiceLinkSource, serviceId: string | null, churchId: string | null, serviceDate: string | null, wasStreamed: boolean | null, setlist: Array<SongUsage>, linkedAt: number, };
