// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The source of a [`ServiceLink`]. Mirrors the renderer `ServiceLink['source']`.
 */
export type ServiceLinkSource = "stage" | "plan" | "manual";
