// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A timer instruction the host layer should act on. Arming an already-armed
 * timer or cancelling a non-existent one is never emitted — the watcher
 * tracks that itself, so the host can act on these naively.
 */
export type SilenceAction = "arm_stop" | "arm_warn" | "cancel_stop" | "cancel_warn";
