// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The two events we extract from ffmpeg's `silencedetect` stderr output.
 */
export type SilenceEvent = "start" | "end";
