// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The sleep/power configuration the UI surfaces (with "fix" buttons). Mirrors
 * the Electron `SleepConfig`; every probe is optional so a partial read still
 * renders. `wakeTimersEnabled` is Windows-only; the mac fields are macOS-only.
 */
export type SleepConfig = { autopoweroff: boolean | null, autopoweroffDelay: number | null, standby: boolean | null, standbyDelay: number | null, hibernateMode: number | null, wakeTimersEnabled: boolean | null, error: string | null, };
