// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A song used in a service, with the cross-suite identifiers we may know.
 * Mirrors the renderer `SongUsage` (camelCase) and the platform contract.
 */
export type SongUsage = { title: string, tonoWorkId: string | null, ccliSongId: string | null, sundaysongId: string | null, firstShownSec: bigint | null, displayedSec: bigint | null, };
