// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A one-off dated recording. Mirrors the Electron `SpecialRecording`
 * (`types/index.ts:25`): `{ id?; date; name; start; stop; deviceId? }`.
 */
export type SpecialRecording = { 
/**
 * Stable id (UI-generated), optional for older stored entries.
 */
id: string | null, 
/**
 * Calendar date `YYYY-MM-DD`.
 */
date: string, 
/**
 * Human-readable label shown in history / notifications.
 */
name: string, 
/**
 * Start time `HH:MM`.
 */
start: string, 
/**
 * Stop time `HH:MM`.
 */
stop: string, 
/**
 * Optional capture-device override for this recording.
 */
deviceId: string | null, };
