// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output resolution preset. Mirrors the Electron `RES_MAP` keys.
 */
export type StreamResolution = "p480" | "p720" | "p1080";
