// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DestinationHealth } from "./DestinationHealth";

/**
 * Live stream status surfaced to the renderer. Mirrors the Electron
 * `StreamStats` (sans the per-line churn). `active` is the single source of
 * truth for the start/stop button.
 */
export type StreamStatus = { active: boolean, 
/**
 * Epoch-ms when the current stream started, or `None`.
 */
startedAt: bigint | null, 
/**
 * Most recent total bitrate (kbps).
 */
bitrateKbps: number, 
/**
 * Most recent encoder FPS.
 */
fps: number, 
/**
 * Frames dropped so far.
 */
dropped: number, 
/**
 * Last interesting stderr line (e.g. a connection error), key-redacted.
 */
lastLine: string, 
/**
 * Per-destination liveness, in pushable order. Empty when idle.
 */
destinations: Array<DestinationHealth>, 
/**
 * The video bitrate (kbps) ffmpeg is currently *targeting*. Starts at the
 * configured/auto bitrate and drops a tier each time the adaptive-bitrate
 * supervisor steps down under sustained network stress. Distinct from
 * `bitrateKbps` (the measured live rate). 0 when idle.
 */
targetBitrateKbps: number, 
/**
 * Which adaptive-bitrate degradation tier the stream is on: 0 = full
 * quality, 1/2 = stepped down under stress. Lets the UI show "Redusert
 * kvalitet" instead of a silently-degraded stream.
 */
bitrateStep: number, };
