// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a stream key / RTMP URL was rejected. Stable so the renderer can map to
 * a localized message without parsing free text.
 */
export type StreamKeyError = "empty" | "has_whitespace" | "too_short" | "bad_scheme";
