// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a test recording failed. Mirrors the Electron error strings so the
 * renderer's i18n keys carry across unchanged.
 */
export type TestRecordingError = "device_not_found" | "device_permission_denied" | "ffmpeg_error" | "no_audio";
