// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The outcome of scheduling a manual test-wake. Mirrors the Electron
 * `testWake`'s return: on success a `jobId` the renderer can cancel, plus the
 * scheduled wall-clock time the resume handler will compare against.
 */
export type TestWakeResult = { ok: boolean, 
/**
 * Opaque id the renderer passes to `wake_cancel_test`.
 */
jobId: string | null, 
/**
 * ISO-like local string of the scheduled wake.
 */
scheduledAt: string | null, reason: string | null, };
