// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Measured signal strength of a test recording. Mirrors the Electron
 * `'silent' | 'low' | 'normal'` union.
 */
export type TestRecordingSignal = "silent" | "low" | "normal";
