// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Capture host platform for the one platform-dependent timeout (startup).
 */
export type TimeoutPlatform = "windows" | "other";
