// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A token set as returned by the Google token endpoint, with `expires_in`
 * already resolved to an absolute `expires_at` (unix ms). Mirrors the shape
 * `exchangeCode`/`refreshAccessToken` resolve in `oauth.ts`.
 */
export type TokenResponse = { access_token: string, 
/**
 * Absent on refresh responses that don't rotate the refresh token.
 */
refresh_token: string | null, 
/**
 * Unix ms when the access token expires; `None` if the endpoint omitted
 * `expires_in`.
 */
expires_at: number | null, };
