// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One transcript segment. Mirrors the renderer `TranscriptSegment` (seconds).
 */
export type TranscriptSegment = { start: number, end: number, text: string, };
