// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptSegment } from "./TranscriptSegment";

/**
 * Sidecar written alongside the recording at `<name>.transcript.json`. Mirrors
 * the renderer `TranscriptData` (schema version 1).
 */
export type TranscriptData = { 
/**
 * Schema version (always 1 today). Field kept first to match the JSON shape.
 */
version: number, model: string, language: string, duration: number, createdAt: number, translated: boolean | null, segments: Array<TranscriptSegment>, };
