// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a queue entry is in its lifecycle. Serialised kebab-case to match the
 * Electron union `'pending' | 'uploading' | 'failed' | 'reauth-required'`
 * (`types/index.ts:538`).
 */
export type UploadStatus = "pending" | "uploading" | "failed" | "reauth-required";
