// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One usage-log payload (snake_case wire shape SundaySong expects). Mirrors the
 * Electron `UsageLogPayload`.
 */
export type UsageLogPayload = { church_id: string, song_id: string | null, tono_work_id: string | null, ccli_song_id: string | null, title: string | null, service_date: string, duration_displayed_sec: number | null, was_streamed: boolean, idempotency_key: string, };
