// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single VU snapshot, one entry per channel, in dBFS. This is the payload of
 * the `vu://levels` Tauri event. `f32::NEG_INFINITY` (silence) is serialised by
 * serde_json as `null`, which the renderer treats as "-∞ / floor".
 */
export type VuLevels = { 
/**
 * Per-channel peak level since the last sample, in dBFS (≤ 0).
 */
peak_dbfs: Array<number>, 
/**
 * Per-channel RMS level since the last sample, in dBFS (≤ 0).
 */
rms_dbfs: Array<number>, };
