// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The host class for wake purposes. Serialised to the EXACT Electron
 * `WakePlatform` strings (`'mac-arm' | 'mac-intel' | 'win' | 'linux' | 'other'`).
 */
export type WakePlatform = "mac-arm" | "mac-intel" | "win" | "linux" | "other";
