// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of wake outcome a [`WakeFailureEntry`] records. Serialised to the
 * EXACT Electron strings (`'missed' | 'test_ok' | 'test_fail'`).
 */
export type WakeFailureKind = "missed" | "test_ok" | "test_fail";
