// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The outcome of an OS wake-scheduling attempt. Mirrors the Electron `WakeResult`.
 */
export type WakeResult = { ok: boolean, count: number | null, 
/**
 * ISO-like local string of the first/next scheduled wake, or `None`.
 */
nextWake: string | null, 
/**
 * Why it failed: `disabled | cancelled | permission | unsupported | error`.
 */
reason: string | null, message: string | null, };
