// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObservedWake } from "./ObservedWake";

/**
 * The verification snapshot: what we asked the OS to schedule vs what it
 * reports, plus power facts. Mirrors the Electron `WakeStatus` minus the
 * `capabilities` field — the UI reads those from the separate
 * `wake_capabilities` command, so this src-tauri type doesn't embed the
 * core-crate [`WakeCapabilities`] (a cross-crate ts-rs embed produces a broken
 * relative import path; commands returning core types separately are the
 * codebase convention).
 */
export type WakeStatus = { expectedWakes: Array<string>, observedWakes: Array<ObservedWake>, hasMismatch: boolean, onBattery: boolean | null, standbyEnabled: boolean | null, };
