// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WakePlatform } from "./WakePlatform";

/**
 * Honest, OS-grounded statement of what wake can and can't do on this host.
 * Mirrors the Electron `WakeCapabilities`. The `knownIssues`/`recommendations`
 * are user-facing Norwegian, ported verbatim.
 */
export type WakeCapabilities = { platform: WakePlatform, 
/**
 * Wake from S3 sleep — usually true on supported platforms.
 */
canWakeFromSleep: boolean, 
/**
 * Wake from S5 (off) — false on Apple Silicon, BIOS-dependent on Windows.
 */
canWakeFromOff: boolean, 
/**
 * Scheduling wakes typically needs an admin/UAC prompt.
 */
needsAdmin: boolean, knownIssues: Array<string>, recommendations: Array<string>, };
