// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a "fix sleep settings" action.
 */
export type WakeFixResult = { ok: boolean, message: string | null, };
