// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WakeFailureKind } from "./WakeFailureKind";

/**
 * One wake-failure or test-wake outcome. Mirrors the renderer
 * `WakeFailureEntry` (camelCase) field-for-field so saved rows carry across.
 */
export type WakeFailureEntry = { 
/**
 * Unix ms when the outcome was recorded.
 */
timestamp: number, 
/**
 * ISO string — the time the wake was supposed to fire.
 */
scheduledAt: string, 
/**
 * What kind of outcome this is.
 */
kind: WakeFailureKind, 
/**
 * Human-readable label (slot name, "Spesialopptak", "Test-wake").
 */
label: string, 
/**
 * Free-form reason (e.g. `no_resume`, `too_late`, `on_battery`).
 */
reason: string | null, 
/**
 * Actual delta in seconds between expected and observed (test-wake only).
 */
deltaSec: number | null, };
