// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WhisperQuality } from "./WhisperQuality";

/**
 * One curated whisper.cpp model. Mirrors `whisper-models.ts` `WhisperModelMeta`
 * field-for-field (camelCase on the wire) so the saved selection + the model
 * files (`ggml-<id>.bin`) carry across the migration unchanged.
 */
export type WhisperModelMeta = { 
/**
 * Stable id used by IPC + the on-disk `<id>.bin` file.
 */
id: string, 
/**
 * User-facing label.
 */
label: string, 
/**
 * Brief description shown in the model-picker.
 */
description: string, 
/**
 * Download URL (Hugging Face LFS resolve).
 */
url: string, 
/**
 * Exact file size in bytes — renders "X / Y MB" + lets a status check
 * confirm a file without re-hashing hundreds of MB.
 */
sizeBytes: number, 
/**
 * SHA-256 of the model file (lowercase hex). Verified after download.
 */
sha256: string, 
/**
 * Relative speed score (1.0 = real-time on M1 Pro w/ Metal). Higher = faster.
 */
realtimeFactor: number, 
/**
 * Quality tier — drives the "Recommended" badge.
 */
quality: WhisperQuality, };
