// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quality tier — informational, drives the "Recommended" badge. Serialised
 * lowercase to match the Electron strings (`'low' | 'medium' | 'high' | 'best'`).
 */
export type WhisperQuality = "low" | "medium" | "high" | "best";
