// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Installed-status for one model. Mirrors `whisper-models.ts` `InstalledStatus`.
 * `size_ok` is true when the file on disk has the expected byte length — we do
 * NOT re-hash on every status check (that would re-read hundreds of MB).
 */
export type InstalledStatus = { id: string, installed: boolean, sizeOk: boolean, };
